### ISSUE TITLE
reply to

### ISSUE THREAD

**Issue by GemmaCowton** [castlegateit/cgit-static-site-template#3]
I think the reply to address needs changing.

The reply to address should be the email address submitted in the form. Can that be added as a variable in the config file? I presume not. Therefore the template would need changing to add the reply to field in the contact form after the fields are defined.

The config file could just contain a true or false to turn the reply to email function on..

Does that make sense? Or have I misunderstood the use.

**Comment by johnkhughes** [comment]
You *can* set the reply to address just as you say. The default value of `false` just means "don't use a reply-to address".
